version: "3.9"
services:
  iventoy:
    image: cola16/iventoy-debian:debian-bookworm-slim-2023-1220-3
    restart: always
    ports:
      - 16000:16000
      - 26000:26000
      #- target: 16000
      #  published: 16000
      #  mode: host
      #  protocol: tcp
      #- target: 26000
      #  published: 26000
      #  mode: host
      #  protocol: tcp
    volumes:
      - /share/NoSnap-Tier/box-backup/backup/Files/OSx64:/app/iso/amd64
      - /share/NoSnap-Tier/box-backup/backup/Files/OSaarch64:/app/iso/arm64
      - ./app-data:/app/data
    environment:
      - AUTO_START_PXE=true
    privileged: true
